spring:
  profiles: 
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: service-rss-reader
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-rss-reader
server:
  port: 8762
rss:
  reader:
    url: ENC(t33192tsbdfo1CWtTi/wE2wfCPyteZfTDyp8KbpztcvUaAoE/bh1VLSEodQJM98vwUfYYBrepF73kRqBgafYtx5QGXBO71Kv)
---
spring: 
  profiles: dev  
amazon:
  dynamodb:
    endpoint: http://localhost:33000/
    location: ap-south-1
  aws:
    accesskey: xskCMievjQcKABonsdf3nsVhe7LRdOb5OWH4ysqW
    secretkey: ENC(6mPLYf51WVS9QUP7nfcgyt50ugZx/pVI)
---
spring: 
  profiles: prod  
amazon:
  dynamodb:
    endpoint: ENC(nVi2J9RZcoAkQ/02B/rxkHm+1KHauKEuObjUqEfdsztmnGFpGbXG7Q==)
    location: ap-south-1
  aws:
    accesskey: xskCMievjQcKABonsdf3nsVhe7LRdOb5OWH4ysqW
    secretkey: ENC(6mPLYf51WVS9QUP7nfcgyt50ugZx/pVI)
eureka:
  instance:
    hostname: ENC(1JypzSnMMiWY+x1fGTnJuMFVRODMR2Jl)
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/