spring:
  application:
    name: service-zuul-server
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-zuul-server
zuul:
  routes:
    data:
      path: /api/v1/**
      serviceId: service-jobad-reader
server:
  port: 8766
