spring:
  profiles: 
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: service-rss-reader
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    instance:
      appname: service-rss-reader
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 8762
rss:
  reader:
    url: ENC(t33192tsbdfo1CWtTi/wE2wfCPyteZfTDyp8KbpztcvUaAoE/bh1VLSEodQJM98vwUfYYBrepF73kRqBgafYtx5QGXBO71Kv)
mongodb:
  host: ENC(oXYwgkqavDow85fxwV0eSDCvVlKF4tjT)
  port: ENC(YWpoI5+wFnm3ek2l2IRtpQ==)
  db: service-rss-reader-${spring.profiles.active}
  auth:
    username:
    password:
    db: service-rss-reader-${spring.profiles.active}
---
spring:
  profiles: prod
eureka:
  instance:
    hostname: ENC(1JypzSnMMiWY+x1fGTnJuMFVRODMR2Jl)