spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: service-rss-reader
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-rss-reader
server:
  port: 8762
rss:
  reader:
    url: https://hk.jobsdb.com/HK/en/Rss/JobListing?jobFunctionId=131
mongodb:
  db: service-rss-reader-${spring.profiles.active}
  auth:
    db: service-rss-reader-${spring.profiles.active}
