spring:
  application:
    name: service-zuul-server
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-zuul-server
zuul:
  ignored-services: "*"
  routes:
    jobad-reader:
      path: /rest/**
      service-id: service-jobad-reader
server:
  port: 8766
ribbon:
  ReadTimeout: 6000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
