spring:
  application:
    name: service-zuul-server

eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-zuul-server

zuul:
  routes:
    api-a:
      path: /api-a/**
      url: https://www.google.com/

server:
  port: 8766
