spring:
  application:
    name: service-zuul-server
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-zuul-server
zuul:
  routes:
    data:
      path: /data/**
      serviceId: service-jobad-reader
      stripPrefix: false
server:
  port: 8766
