spring:
  application:
    name: service-zuul-server

eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-zuul-server

zuul:
  ignored-services: "*"
  routes:
    data:
      prefix: /api/v1
      path: /data/**
      service-id: service-jobad-reader
      stripPrefix: true
      

server:
  port: 8766
