spring:
  profiles: 
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-rss-reader
server:
  port: 8762
rss:
  reader:
    url: ENC(t33192tsbdfo1CWtTi/wE2wfCPyteZfTDyp8KbpztcvUaAoE/bh1VLSEodQJM98vwUfYYBrepF73kRqBgafYtx5QGXBO71Kv)
amazon:
  dynamodb:
    endpoint: http://localhost:33000/
    location: ap-south-1
  aws:
    accesskey: xskCMievjQcKABonsdf3nsVhe7LRdOb5OWH4ysqW
    secretkey: ENC(6mPLYf51WVS9QUP7nfcgyt50ugZx/pVI)