spring:
  application:
    name: service-zuul-server

eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-zuul-server

zuul:
  routes:
    jobad-reader:
      path: /rest/**
      service-id: service-jobad-reader

server:
  port: 8766

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
