spring:
  application:
    name: service-zuul-server

eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-zuul-server

zuul:
  ignored-services: "*"
  routes:
    jobad-reader:
      path: /rest/**
      service-id: service-jobad-reader

server:
  port: 8766
  address: 0.0.0.0
