spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: service-eureka-scheduler
  devtools:
    restart:
      enabled: false
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-eureka-scheduler
server:
  port: 8763
scheduler:
  enable: true
  configList:
    - service-jobad-reader
  configMap:
    service-jobad-reader:
      name: service-jobad-reader
      rate: 1800000
      path: /api/v1/batch/update-jobads