spring:
  profiles: 
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: service-eureka-scheduler
  devtools:
    restart:
      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    instance:
      appname: service-eureka-scheduler
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 8763
scheduler:
  enable: true
  configList:
    - service-jobad-reader
  configMap:
    service-jobad-reader:
      name: service-jobad-reader
      rate: 1800000
      path: /api/v1/batch/update-jobads
---
spring:
  profiles: prod
eureka:
  instance:
    hostname: ENC(1JypzSnMMiWY+x1fGTnJuMFVRODMR2Jl)
  service-url:
    defaultZone: http://${eureka.instance.hostname}:8761/eureka/