spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: service-rss-reader
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-rss-reader
server:
  port: 8762
rss:
  reader:
    url: ENC(t33192tsbdfo1CWtTi/wE2wfCPyteZfTDyp8KbpztcvUaAoE/bh1VLSEodQJM98vwUfYYBrepF73kRqBgafYtx5QGXBO71Kv)