spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: service-rss-reader
eureka:
  client:
    register-with-eureka: true
    instance:
      appname: service-rss-reader
server:
  port: 8762
rss:
  reader:
    url: https://hk.jobsdb.com/HK/en/Rss/JobListing?jobFunctionId=131
mongodb:
  db: service-rss-reader-${spring.profiles.active}
  auth:
    db: service-rss-reader-${spring.profiles.active}
com.dotterbear.rss.reader:
  deserializer:
    jobsdb:
      date-time: EEE, dd MMM yyyy HH:mm:ss z
  serializer:
    date-time: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
