spring:
  profiles: 
    active: prod
mongodb:
  host: 127.0.0.1
  port: 27017
  auth:
    username: myUserAdmin
    password: abc123
    db: admin
eureka:
  instance:
    hostname: 127.0.0.1
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
